name: dart_cli_task_manager
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.7.0

dependencies:
  uuid: ^4.5.2

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
